[loggers]
keys=root,app,scheduler,worker,api

[handlers]
keys=console

[formatters]
keys=standard

[logger_root]
level=%(log_level)s
handlers=console

[logger_app]
level=%(log_level)s
handlers=console
qualname=app
propagate=0

[logger_scheduler]
level=%(log_level)s
handlers=console
qualname=scheduler
propagate=0

[logger_worker]
level=%(log_level)s
handlers=console
qualname=worker
propagate=0

[logger_api]
level=%(log_level)s
handlers=console
qualname=api
propagate=0

[handler_console]
class=StreamHandler
level=%(log_level)s
formatter=standard
args=(sys.stdout,)

[formatter_standard]
format=%(asctime)s %(levelname)s [%(name)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
